{% set name = "aplpy" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 282766070416b7b21f1ec8eaee95a56d22121297d0643cadf924124c3694095e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - setuptools_scm
    - wheel
  run:
    - python >=3.6
    - numpy
    - astropy >=3.1
    - matplotlib-base >=2.0
    - reproject >=0.4
    - pyregion >=2.0
    - pillow >=4.3
    - pyavm >=0.9.4
    - scikit-image >=0.14
    - shapely >=1.7

test:
  imports:
    - aplpy

about:
  home: http://aplpy.github.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: The Astronomical Plotting Library in Python
  description: |
    APLpy (the Astronomical Plotting Library in Python) is a Python module
    aimed at producing publication-quality plots of astronomical imaging data
    in FITS format.
  doc_url: http://aplpy.readthedocs.io
  dev_url: https://github.com/aplpy/aplpy

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - astrofrog
